"""Iceberg Drift Prediction - AI-enabled Antarctic navigation decision support."""

__version__ = "0.1.0"
__author__ = "Antarctic Navigation DSS Team"

from .config import get_config, load_config, Config
from .data_processing import (
    download_iceberg_positions,
    download_era5_wind,
    download_copernicus_currents,
    download_bathymetry,
    match_environmental_data,
    engineer_features,
    create_targets,
    split_trajectories,
    get_feature_columns,
    scale_features,
    IcebergDriftDataset,
    create_dataloaders,
    # Quality
    check_iceberg_data_quality,
    resample_iceberg_trajectory,
    filter_coastal_nan,
    fill_coastal_current_nan,
    check_environmental_data_quality,
    DataQualityPipeline,
    validate_and_clean_iceberg_data,
    create_quality_report,
)
from .models import (
    PhysicsDriftModel,
    LSTMDriftModel,
    GRUDriftModel,
    TransformerDriftModel,
    MLPDriftModel,
    PINNDriftModel,
    HybridDriftModel,
    EnsembleDriftModel,
    create_model,
    # GBM models
    GBMConfig,
    GBMModelResult,
    XGBoostRegressor,
    LightGBMRegressor,
    MultiTargetGBM,
    PhysicsInformedGBM,
    EnsembleGBM,
    create_gbm_model,
    create_gbm_config,
)
from .evaluation import (
    DriftTrainer,
    DriftValidator,
    compute_all_metrics,
    train_model,
    validate_model,
    TrainingConfig,
    ValidationConfig,
)
from .utils import (
    DriftPredictor,
    load_model_for_inference,
    plot_trajectory,
    plot_trajectory_comparison,
    create_trajectory_animation,
    export_to_geojson,
    export_to_netcdf,
    export_to_csv,
    export_route_for_navigation,
)

__all__ = [
    # Config
    "get_config",
    "load_config",
    "Config",
    # Data processing
    "download_iceberg_positions",
    "download_era5_wind",
    "download_copernicus_currents",
    "download_bathymetry",
    "match_environmental_data",
    "engineer_features",
    "create_targets",
    "split_trajectories",
    "get_feature_columns",
    "scale_features",
    "IcebergDriftDataset",
    "create_dataloaders",
    # Quality
    "check_iceberg_data_quality",
    "resample_iceberg_trajectory",
    "filter_coastal_nan",
    "fill_coastal_current_nan",
    "check_environmental_data_quality",
    "DataQualityPipeline",
    "validate_and_clean_iceberg_data",
    "create_quality_report",
    # Models
    "PhysicsDriftModel",
    "LSTMDriftModel",
    "GRUDriftModel",
    "TransformerDriftModel",
    "MLPDriftModel",
    "PINNDriftModel",
    "HybridDriftModel",
    "EnsembleDriftModel",
    "create_model",
    # GBM models
    "GBMConfig",
    "GBMModelResult",
    "XGBoostRegressor",
    "LightGBMRegressor",
    "MultiTargetGBM",
    "PhysicsInformedGBM",
    "EnsembleGBM",
    "create_gbm_model",
    "create_gbm_config",
    # Evaluation
    "DriftTrainer",
    "DriftValidator",
    "compute_all_metrics",
    "train_model",
    "validate_model",
    "TrainingConfig",
    "ValidationConfig",
    # Utils
    "DriftPredictor",
    "load_model_for_inference",
    "plot_trajectory",
    "plot_trajectory_comparison",
    "create_trajectory_animation",
    "export_to_geojson",
    "export_to_netcdf",
    "export_to_csv",
    "export_route_for_navigation",
]